# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Past',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('your_age', models.TextField(max_length=500)),
            ],
        ),
    ]
